CREATE TABLE countries (
"code" varchar(2) NOT NULL default '',
"englishName" varchar(100) NOT NULL default '',
"arabicName" varchar(100) NOT NULL default '',
"englishNationality" varchar(100) NOT NULL default '',
"arabicNationality" varchar(100) NOT NULL default '',
PRIMARY KEY ("code")
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-- 


INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AF', 'Afghanistan','أفغانستان','Afghan','أفغانستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AL', 'Albania','ألبانيا','Albanian','ألباني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AX', 'Aland Islands','جزر آلاند','Aland Islander','آلاندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DZ', 'Algeria','الجزائر','Algerian','جزائري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AS', 'American Samoa','ساموا-الأمريكي','American Samoan','أمريكي سامواني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AD', 'Andorra','أندورا','Andorran','أندوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AO', 'Angola','أنغولا','Angolan','أنقولي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AI', 'Anguilla','أنغويلا','Anguillan','أنغويلي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AQ', 'Antarctica','أنتاركتيكا','Antarctican','أنتاركتيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AG', 'Antigua and Barbuda','أنتيغوا وبربودا','Antiguan','بربودي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AR', 'Argentina','الأرجنتين','Argentinian','أرجنتيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AM', 'Armenia','أرمينيا','Armenian','أرميني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AW', 'Aruba','أروبه','Aruban','أوروبهيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AU', 'Australia','أستراليا','Australian','أسترالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AT', 'Austria','النمسا','Austrian','نمساوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AZ', 'Azerbaijan','أذربيجان','Azerbaijani','أذربيجاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BS', 'Bahamas','الباهاماس','Bahamian','باهاميسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BH', 'Bahrain','البحرين','Bahraini','بحريني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BD', 'Bangladesh','بنغلاديش','Bangladeshi','بنغلاديشي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BB', 'Barbados','بربادوس','Barbadian','بربادوسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BY', 'Belarus','روسيا البيضاء','Belarusian','روسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BE', 'Belgium','بلجيكا','Belgian','بلجيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BZ', 'Belize','بيليز','Belizean','بيليزي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BJ', 'Benin','بنين','Beninese','بنيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" ,  "english_nationality" , "arabic_nationality") VALUES ('BL', 'Saint Barthelemy','سان بارتيلمي','Saint Barthelmian','سان بارتيلمي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BM', 'Bermuda','جزر برمودا','Bermudan','برمودي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BT', 'Bhutan','بوتان','Bhutanese','بوتاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BO', 'Bolivia','بوليفيا','Bolivian','بوليفي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BA', 'Bosnia and Herzegovina','البوسنة و الهرسك','Bosnian / Herzegovinian','بوسني/هرسكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BW', 'Botswana','بوتسوانا','Botswanan','بوتسواني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BV', 'Bouvet Island','جزيرة بوفيه','Bouvetian','بوفيهي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BR', 'Brazil','البرازيل','Brazilian','برازيلي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IO', 'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني','British Indian Ocean Territory','إقليم المحيط الهندي البريطاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BN', 'Brunei Darussalam','بروني','Bruneian','بروني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BG', 'Bulgaria','بلغاريا','Bulgarian','بلغاري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BF', 'Burkina Faso','بوركينا فاسو','Burkinabe','بوركيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('BI', 'Burundi','بوروندي','Burundian','بورونيدي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KH', 'Cambodia','كمبوديا','Cambodian','كمبودي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CM', 'Cameroon','كاميرون','Cameroonian','كاميروني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CA', 'Canada','كندا','Canadian','كندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CV', 'Cape Verde','الرأس الأخضر','Cape Verdean','الرأس الأخضر');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KY', 'Cayman Islands','جزر كايمان','Caymanian','كايماني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CF', 'Central African Republic','جمهورية أفريقيا الوسطى','Central African','أفريقي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TD', 'Chad','تشاد','Chadian','تشادي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CN', 'China','الصين','Chinese','صيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CX', 'Christmas Island','جزيرة عيد الميلاد','Christmas Islander','جزيرة عيد الميلاد');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CC', 'Cocos (Keeling) Islands','جزر كوكوس','Cocos Islander','جزر كوكوس');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CO', 'Colombia','كولومبيا','Colombian','كولومبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KM', 'Comoros','جزر القمر','Comorian','جزر القمر');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CG', 'Congo','الكونغو','Congolese','كونغي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CK', 'Cook Islands','جزر كوك','Cook Islander','جزر كوك');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CR', 'Costa Rica','كوستاريكا','Costa Rican','كوستاريكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HR', 'Croatia','كرواتيا','Croatian','كوراتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CU', 'Cuba','كوبا','Cuban','كوبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CY', 'Cyprus','قبرص','Cypriot','قبرصي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CW', 'Curaçao','كوراساو','Curacian','كوراساوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CZ', 'Czech Republic','الجمهورية التشيكية','Czech','تشيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DK', 'Denmark','الدانمارك','Danish','دنماركي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DJ', 'Djibouti','جيبوتي','Djiboutian','جيبوتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DM', 'Dominica','دومينيكا','Dominican','دومينيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DO', 'Dominican Republic','الجمهورية الدومينيكية','Dominican','دومينيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('EC', 'Ecuador','إكوادور','Ecuadorian','إكوادوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('EG', 'Egypt','مصر','Egyptian','مصري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SV', 'El Salvador','إلسلفادور','Salvadoran','سلفادوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GQ', 'Equatorial Guinea','غينيا الاستوائي','Equatorial Guinean','غيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ER', 'Eritrea','إريتريا','Eritrean','إريتيري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('EE', 'Estonia','استونيا','Estonian','استوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ET', 'Ethiopia','أثيوبيا','Ethiopian','أثيوبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FK', 'Falkland Islands (Malvinas)','جزر فوكلاند','Falkland Islander','فوكلاندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FO', 'Faroe Islands','جزر فارو','Faroese','جزر فارو');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FJ', 'Fiji','فيجي','Fijian','فيجي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FI', 'Finland','فنلندا','Finnish','فنلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FR', 'France','فرنسا','French','فرنسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GF', 'French Guiana','غويانا الفرنسية','French Guianese','غويانا الفرنسية');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PF', 'French Polynesia','بولينيزيا الفرنسية','French Polynesian','بولينيزيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TF', 'French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية','French','أراض فرنسية جنوبية وأنتارتيكية');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GA', 'Gabon','الغابون','Gabonese','غابوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GM', 'Gambia','غامبيا','Gambian','غامبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GE', 'Georgia','جيورجيا','Georgian','جيورجي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('DE', 'Germany','ألمانيا','German','ألماني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GH', 'Ghana','غانا','Ghanaian','غاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GI', 'Gibraltar','جبل طارق','Gibraltar','جبل طارق');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GG', 'Guernsey','غيرنزي','Guernsian','غيرنزي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GR', 'Greece','اليونان','Greek','يوناني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GL', 'Greenland','جرينلاند','Greenlandic','جرينلاندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GD', 'Grenada','غرينادا','Grenadian','غرينادي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GP', 'Guadeloupe','جزر جوادلوب','Guadeloupe','جزر جوادلوب');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GU', 'Guam','جوام','Guamanian','جوامي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GT', 'Guatemala','غواتيمال','Guatemalan','غواتيمالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GN', 'Guinea','غينيا','Guinean','غيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GW', 'Guinea-Bissau','غينيا-بيساو','Guinea-Bissauan','غيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GY', 'Guyana','غيانا','Guyanese','غياني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HT', 'Haiti','هايتي','Haitian','هايتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HM', 'Heard and Mc Donald Islands','جزيرة هيرد وجزر ماكدونالد','Heard and Mc Donald Islanders','جزيرة هيرد وجزر ماكدونالد');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HN', 'Honduras','هندوراس','Honduran','هندوراسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HK', 'Hong Kong','هونغ كونغ','Hongkongese','هونغ كونغي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('HU', 'Hungary','المجر','Hungarian','مجري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IS', 'Iceland','آيسلندا','Icelandic','آيسلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IN', 'India','الهند','Indian','هندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IM', 'Isle of Man','جزيرة مان','Manx','ماني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ID', 'Indonesia','أندونيسيا','Indonesian','أندونيسيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IR', 'Iran','إيران','Iranian','إيراني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IQ', 'Iraq','العراق','Iraqi','عراقي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IE', 'Ireland','إيرلندا','Irish','إيرلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IL', 'Israel','إسرائيل','Israeli','إسرائيلي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('IT', 'Italy','إيطاليا','Italian','إيطالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CI', 'Ivory Coast','ساحل العاج','Ivory Coastian','ساحل العاج');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('JE', 'Jersey','جيرزي','Jersian','جيرزي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('JM', 'Jamaica','جمايكا','Jamaican','جمايكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('JP', 'Japan','اليابان','Japanese','ياباني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('JO', 'Jordan','الأردن','Jordanian','أردني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KZ', 'Kazakhstan','كازاخستان','Kazakh','كازاخستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KE', 'Kenya','كينيا','Kenyan','كيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KI', 'Kiribati','كيريباتي','I-Kiribati','كيريباتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KP', 'Korea(North Korea)','كوريا الشمالية','North Korean','كوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KR', 'Korea(South Korea)','كوريا الجنوبية','South Korean','كوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('XK', 'Kosovo','كوسوفو','Kosovar','كوسيفي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KW', 'Kuwait','الكويت','Kuwaiti','كويتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KG', 'Kyrgyzstan','قيرغيزستان','Kyrgyzstani','قيرغيزستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LA', 'Lao PDR','لاوس','Laotian','لاوسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LV', 'Latvia','لاتفيا','Latvian','لاتيفي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LB', 'Lebanon','لبنان','Lebanese','لبناني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LS', 'Lesotho','ليسوتو','Basotho','ليوسيتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LR', 'Liberia','ليبيريا','Liberian','ليبيري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LY', 'Libya','ليبيا','Libyan','ليبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LI', 'Liechtenstein','ليختنشتين','Liechtenstein','ليختنشتيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LT', 'Lithuania','لتوانيا','Lithuanian','لتوانيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LU', 'Luxembourg','لوكسمبورغ','Luxembourger','لوكسمبورغي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LK', 'Sri Lanka','سريلانكا','Sri Lankian','سريلانكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MO', 'Macau','ماكاو','Macanese','ماكاوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MK', 'Macedonia','مقدونيا','Macedonian','مقدوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MG', 'Madagascar','مدغشقر','Malagasy','مدغشقري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MW', 'Malawi','مالاوي','Malawian','مالاوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MY', 'Malaysia','ماليزيا','Malaysian','ماليزي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MV', 'Maldives','المالديف','Maldivian','مالديفي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ML', 'Mali','مالي','Malian','مالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MT', 'Malta','مالطا','Maltese','مالطي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MH', 'Marshall Islands','جزر مارشال','Marshallese','مارشالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MQ', 'Martinique','مارتينيك','Martiniquais','مارتينيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MR', 'Mauritania','موريتانيا','Mauritanian','موريتانيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MU', 'Mauritius','موريشيوس','Mauritian','موريشيوسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('YT', 'Mayotte','مايوت','Mahoran','مايوتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MX', 'Mexico','المكسيك','Mexican','مكسيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('FM', 'Micronesia','مايكرونيزيا','Micronesian','مايكرونيزيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MD', 'Moldova','مولدافيا','Moldovan','مولديفي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MC', 'Monaco','موناكو','Monacan','مونيكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MN', 'Mongolia','منغوليا','Mongolian','منغولي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ME', 'Montenegro','الجبل الأسود','Montenegrin','الجبل الأسود');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MS', 'Montserrat','مونتسيرات','Montserratian','مونتسيراتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MA', 'Morocco','المغرب','Moroccan','مغربي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MZ', 'Mozambique','موزمبيق','Mozambican','موزمبيقي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MM', 'Myanmar','ميانمار','Myanmarian','ميانماري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NA', 'Namibia','ناميبيا','Namibian','ناميبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NR', 'Nauru','نورو','Nauruan','نوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NP', 'Nepal','نيبال','Nepalese','نيبالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NL', 'Netherlands','هولندا','Dutch','هولندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AN', 'Netherlands Antilles','جزر الأنتيل الهولندي','Dutch Antilier','هولندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NC', 'New Caledonia','كاليدونيا الجديدة','New Caledonian','كاليدوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NZ', 'New Zealand','نيوزيلندا','New Zealander','نيوزيلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NI', 'Nicaragua','نيكاراجوا','Nicaraguan','نيكاراجوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NE', 'Niger','النيجر','Nigerien','نيجيري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NG', 'Nigeria','نيجيريا','Nigerian','نيجيري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NU', 'Niue','ني','Niuean','ني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NF', 'Norfolk Island','جزيرة نورفولك','Norfolk Islander','نورفوليكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MP', 'Northern Mariana Islands','جزر ماريانا الشمالية','Northern Marianan','ماريني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('NO', 'Norway','النرويج','Norwegian','نرويجي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('OM', 'Oman','عمان','Omani','عماني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PK', 'Pakistan','باكستان','Pakistani','باكستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PW', 'Palau','بالاو','Palauan','بالاوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PS', 'Palestine','فلسطين','Palestinian','فلسطيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PA', 'Panama','بنما','Panamanian','بنمي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PG', 'Papua New Guinea','بابوا غينيا الجديدة','Papua New Guinean','بابوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PY', 'Paraguay','باراغواي','Paraguayan','بارغاوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PE', 'Peru','بيرو','Peruvian','بيري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PH', 'Philippines','الفليبين','Filipino','فلبيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PN', 'Pitcairn','بيتكيرن','Pitcairn Islander','بيتكيرني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PL', 'Poland','بولندا','Polish','بولندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PT', 'Portugal','البرتغال','Portuguese','برتغالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('PR', 'Puerto Rico','بورتو ريكو','Puerto Rican','بورتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('QA', 'Qatar','قطر','Qatari','قطري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('RE', 'Reunion Island','ريونيون','Reunionese','ريونيوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('RO', 'Romania','رومانيا','Romanian','روماني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('RU', 'Russian','روسيا','Russian','روسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('RW', 'Rwanda','رواندا','Rwandan','رواندا');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('KN', 'Saint Kitts and Nevis','سانت كيتس ونيفس,','Kittitian/Nevisian','سانت كيتس ونيفس');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('MF', 'Saint Martin (French part)','ساينت مارتن فرنسي','St. Martian(French)','ساينت مارتني فرنسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SX', 'Sint Maarten (Dutch part)','ساينت مارتن هولندي','St. Martian(Dutch)','ساينت مارتني هولندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('LC', 'Saint Pierre and Miquelon','سان بيير وميكلون','St. Pierre and Miquelon','سان بيير وميكلوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VC', 'Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين','Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('WS', 'Samoa','ساموا','Samoan','ساموي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SM', 'San Marino','سان مارينو','Sammarinese','ماريني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ST', 'Sao Tome and Principe','ساو تومي وبرينسيبي','Sao Tomean','ساو تومي وبرينسيبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SA', 'Saudi Arabia','المملكة العربية السعودية','Saudi Arabian','سعودي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SN', 'Senegal','السنغال','Senegalese','سنغالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('RS', 'Serbia','صربيا','Serbian','صربي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SC', 'Seychelles','سيشيل','Seychellois','سيشيلي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SL', 'Sierra Leone','سيراليون','Sierra Leonean','سيراليوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SG', 'Singapore','سنغافورة','Singaporean','سنغافوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SK', 'Slovakia','سلوفاكيا','Slovak','سولفاكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SI', 'Slovenia','سلوفينيا','Slovenian','سولفيني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SB', 'Solomon Islands','جزر سليمان','Solomon Island','جزر سليمان');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SO', 'Somalia','الصومال','Somali','صومالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ZA', 'South Africa','جنوب أفريقيا','South African','أفريقي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GS', 'South Georgia and the South Sandwich','المنطقة القطبية الجنوبية','South Georgia and the South Sandwich','لمنطقة القطبية الجنوبية');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SS', 'South Sudan','السودان الجنوبي','South Sudanese','سوادني جنوبي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ES', 'Spain','إسبانيا','Spanish','إسباني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SH', 'Saint Helena','سانت هيلانة','St. Helenian','هيلاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SD', 'Sudan','السودان','Sudanese','سوداني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SR', 'Suriname','سورينام','Surinamese','سورينامي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SJ', 'Svalbard and Jan Mayen','سفالبارد ويان ماين','Svalbardian/Jan Mayenian','سفالبارد ويان ماين');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SZ', 'Swaziland','سوازيلند','Swazi','سوازيلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SE', 'Sweden','السويد','Swedish','سويدي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('CH', 'Switzerland','سويسرا','Swiss','سويسري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('SY', 'Syria','سوريا','Syrian','سوري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TW', 'Taiwan','تايوان','Taiwanese','تايواني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TJ', 'Tajikistan','طاجيكستان','Tajikistani','طاجيكستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TZ', 'Tanzania','تنزانيا','Tanzanian','تنزانيي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TH', 'Thailand','تايلندا','Thai','تايلندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TL', 'Timor-Leste','تيمور الشرقية','Timor-Lestian','تيموري');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TG', 'Togo','توغو','Togolese','توغي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TK', 'Tokelau','توكيلاو','Tokelaian','توكيلاوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TO', 'Tonga','تونغا','Tongan','تونغي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TT', 'Trinidad and Tobago','ترينيداد وتوباغو','Trinidadian/Tobagonian','ترينيداد وتوباغو');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TN', 'Tunisia','تونس','Tunisian','تونسي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TR', 'Turkey','تركيا','Turkish','تركي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TM', 'Turkmenistan','تركمانستان','Turkmen','تركمانستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TC', 'Turks and Caicos Islands','جزر توركس وكايكوس','Turks and Caicos Islands','جزر توركس وكايكوس');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('TV', 'Tuvalu','توفالو','Tuvaluan','توفالي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('UG', 'Uganda','أوغندا','Ugandan','أوغندي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('UA', 'Ukraine','أوكرانيا','Ukrainian','أوكراني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('AE', 'United Arab Emirates','الإمارات العربية المتحدة','Emirati','إماراتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('GB', 'United Kingdom','المملكة المتحدة','British','بريطاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('US', 'United States','الولايات المتحدة','American','أمريكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('UM', 'US Minor Outlying Islands','قائمة الولايات والمناطق الأمريكية','US Minor Outlying Islander','أمريكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('UY', 'Uruguay','أورغواي','Uruguayan','أورغواي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('UZ', 'Uzbekistan','أوزباكستان','Uzbek','أوزباكستاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VU', 'Vanuatu','فانواتو','Vanuatuan','فانواتي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VE', 'Venezuela','فنزويلا','Venezuelan','فنزويلي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VN', 'Vietnam','فيتنام','Vietnamese','فيتنامي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VI', 'Virgin Islands (U.S.)','الجزر العذراء الأمريكي','American Virgin Islander','أمريكي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('VA', 'Vatican City','فنزويلا','Vatican','فاتيكاني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('WF', 'Wallis and Futuna Islands','والس وفوتونا','Wallisian/Futunan','فوتوني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('EH', 'Western Sahara','الصحراء الغربية','Sahrawian','صحراوي');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('YE', 'Yemen','اليمن','Yemeni','يمني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ZM', 'Zambia','زامبيا','Zambian','زامبياني');
INSERT INTO countries("code" , "english_name" , "arabic_name" , "english_nationality" , "arabic_nationality") VALUES ('ZW', 'Zimbabwe','زمبابوي','Zimbabwean','زمبابوي');
