CREATE TABLE countries (id VARCHAR(64) NOT NULL, value VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `countries` (`id`, `value`) VALUES ('IS', 'آيسلندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ET', 'إثيوبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AZ', 'أذربيجان');
INSERT INTO `countries` (`id`, `value`) VALUES ('AM', 'أرمينيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AW', 'أروبا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ER', 'إريتريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ES', 'إسبانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AU', 'أستراليا');
INSERT INTO `countries` (`id`, `value`) VALUES ('EE', 'إستونيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SZ', 'إسواتيني');
INSERT INTO `countries` (`id`, `value`) VALUES ('AF', 'أفغانستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('PS', 'الأراضي الفلسطينية');
INSERT INTO `countries` (`id`, `value`) VALUES ('AR', 'الأرجنتين');
INSERT INTO `countries` (`id`, `value`) VALUES ('JO', 'الأردن');
INSERT INTO `countries` (`id`, `value`) VALUES ('TF', 'الأقاليم الجنوبية الفرنسية');
INSERT INTO `countries` (`id`, `value`) VALUES ('IO', 'الإقليم البريطاني في المحيط الهندي');
INSERT INTO `countries` (`id`, `value`) VALUES ('EC', 'الإكوادور');
INSERT INTO `countries` (`id`, `value`) VALUES ('AE', 'الإمارات العربية المتحدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('AL', 'ألبانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BH', 'البحرين');
INSERT INTO `countries` (`id`, `value`) VALUES ('BR', 'البرازيل');
INSERT INTO `countries` (`id`, `value`) VALUES ('PT', 'البرتغال');
INSERT INTO `countries` (`id`, `value`) VALUES ('BA', 'البوسنة والهرسك');
INSERT INTO `countries` (`id`, `value`) VALUES ('CZ', 'التشيك');
INSERT INTO `countries` (`id`, `value`) VALUES ('ME', 'الجبل الأسود');
INSERT INTO `countries` (`id`, `value`) VALUES ('DZ', 'الجزائر');
INSERT INTO `countries` (`id`, `value`) VALUES ('DK', 'الدانمرك');
INSERT INTO `countries` (`id`, `value`) VALUES ('CV', 'الرأس الأخضر');
INSERT INTO `countries` (`id`, `value`) VALUES ('SV', 'السلفادور');
INSERT INTO `countries` (`id`, `value`) VALUES ('SN', 'السنغال');
INSERT INTO `countries` (`id`, `value`) VALUES ('SD', 'السودان');
INSERT INTO `countries` (`id`, `value`) VALUES ('SE', 'السويد');
INSERT INTO `countries` (`id`, `value`) VALUES ('EH', 'الصحراء الغربية');
INSERT INTO `countries` (`id`, `value`) VALUES ('SO', 'الصومال');
INSERT INTO `countries` (`id`, `value`) VALUES ('CN', 'الصين');
INSERT INTO `countries` (`id`, `value`) VALUES ('IQ', 'العراق');
INSERT INTO `countries` (`id`, `value`) VALUES ('GA', 'الغابون');
INSERT INTO `countries` (`id`, `value`) VALUES ('VA', 'الفاتيكان');
INSERT INTO `countries` (`id`, `value`) VALUES ('PH', 'الفلبين');
INSERT INTO `countries` (`id`, `value`) VALUES ('CM', 'الكاميرون');
INSERT INTO `countries` (`id`, `value`) VALUES ('CG', 'الكونغو - برازافيل');
INSERT INTO `countries` (`id`, `value`) VALUES ('CD', 'الكونغو - كينشاسا');
INSERT INTO `countries` (`id`, `value`) VALUES ('KW', 'الكويت');
INSERT INTO `countries` (`id`, `value`) VALUES ('DE', 'ألمانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('MA', 'المغرب');
INSERT INTO `countries` (`id`, `value`) VALUES ('MX', 'المكسيك');
INSERT INTO `countries` (`id`, `value`) VALUES ('SA', 'المملكة العربية السعودية');
INSERT INTO `countries` (`id`, `value`) VALUES ('GB', 'المملكة المتحدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('NO', 'النرويج');
INSERT INTO `countries` (`id`, `value`) VALUES ('AT', 'النمسا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NE', 'النيجر');
INSERT INTO `countries` (`id`, `value`) VALUES ('IN', 'الهند');
INSERT INTO `countries` (`id`, `value`) VALUES ('US', 'الولايات المتحدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('JP', 'اليابان');
INSERT INTO `countries` (`id`, `value`) VALUES ('YE', 'اليمن');
INSERT INTO `countries` (`id`, `value`) VALUES ('GR', 'اليونان');
INSERT INTO `countries` (`id`, `value`) VALUES ('AQ', 'أنتاركتيكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AG', 'أنتيغوا وبربودا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AD', 'أندورا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ID', 'إندونيسيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AO', 'أنغولا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AI', 'أنغويلا');
INSERT INTO `countries` (`id`, `value`) VALUES ('UY', 'أورغواي');
INSERT INTO `countries` (`id`, `value`) VALUES ('UZ', 'أوزبكستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('UG', 'أوغندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('UA', 'أوكرانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('IR', 'إيران');
INSERT INTO `countries` (`id`, `value`) VALUES ('IE', 'أيرلندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('IT', 'إيطاليا');
INSERT INTO `countries` (`id`, `value`) VALUES ('PG', 'بابوا غينيا الجديدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('PY', 'باراغواي');
INSERT INTO `countries` (`id`, `value`) VALUES ('PK', 'باكستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('PW', 'بالاو');
INSERT INTO `countries` (`id`, `value`) VALUES ('BB', 'بربادوس');
INSERT INTO `countries` (`id`, `value`) VALUES ('BM', 'برمودا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BN', 'بروناي');
INSERT INTO `countries` (`id`, `value`) VALUES ('BE', 'بلجيكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BG', 'بلغاريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BZ', 'بليز');
INSERT INTO `countries` (`id`, `value`) VALUES ('BD', 'بنغلاديش');
INSERT INTO `countries` (`id`, `value`) VALUES ('PA', 'بنما');
INSERT INTO `countries` (`id`, `value`) VALUES ('BJ', 'بنين');
INSERT INTO `countries` (`id`, `value`) VALUES ('BT', 'بوتان');
INSERT INTO `countries` (`id`, `value`) VALUES ('BW', 'بوتسوانا');
INSERT INTO `countries` (`id`, `value`) VALUES ('PR', 'بورتوريكو');
INSERT INTO `countries` (`id`, `value`) VALUES ('BF', 'بوركينا فاسو');
INSERT INTO `countries` (`id`, `value`) VALUES ('BI', 'بوروندي');
INSERT INTO `countries` (`id`, `value`) VALUES ('PL', 'بولندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BO', 'بوليفيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('PF', 'بولينيزيا الفرنسية');
INSERT INTO `countries` (`id`, `value`) VALUES ('PE', 'بيرو');
INSERT INTO `countries` (`id`, `value`) VALUES ('BY', 'بيلاروس');
INSERT INTO `countries` (`id`, `value`) VALUES ('TH', 'تايلاند');
INSERT INTO `countries` (`id`, `value`) VALUES ('TW', 'تايوان');
INSERT INTO `countries` (`id`, `value`) VALUES ('TM', 'تركمانستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('TR', 'تركيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('TT', 'ترينيداد وتوباغو');
INSERT INTO `countries` (`id`, `value`) VALUES ('TD', 'تشاد');
INSERT INTO `countries` (`id`, `value`) VALUES ('CL', 'تشيلي');
INSERT INTO `countries` (`id`, `value`) VALUES ('TZ', 'تنزانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('TG', 'توغو');
INSERT INTO `countries` (`id`, `value`) VALUES ('TV', 'توفالو');
INSERT INTO `countries` (`id`, `value`) VALUES ('TK', 'توكيلو');
INSERT INTO `countries` (`id`, `value`) VALUES ('TN', 'تونس');
INSERT INTO `countries` (`id`, `value`) VALUES ('TO', 'تونغا');
INSERT INTO `countries` (`id`, `value`) VALUES ('TL', 'تيمور - ليشتي');
INSERT INTO `countries` (`id`, `value`) VALUES ('JM', 'جامايكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GI', 'جبل طارق');
INSERT INTO `countries` (`id`, `value`) VALUES ('AX', 'جزر آلاند');
INSERT INTO `countries` (`id`, `value`) VALUES ('BS', 'جزر البهاما');
INSERT INTO `countries` (`id`, `value`) VALUES ('KM', 'جزر القمر');
INSERT INTO `countries` (`id`, `value`) VALUES ('MQ', 'جزر المارتينيك');
INSERT INTO `countries` (`id`, `value`) VALUES ('MV', 'جزر المالديف');
INSERT INTO `countries` (`id`, `value`) VALUES ('UM', 'جزر الولايات المتحدة النائية');
INSERT INTO `countries` (`id`, `value`) VALUES ('PN', 'جزر بيتكيرن');
INSERT INTO `countries` (`id`, `value`) VALUES ('TC', 'جزر توركس وكايكوس');
INSERT INTO `countries` (`id`, `value`) VALUES ('SB', 'جزر سليمان');
INSERT INTO `countries` (`id`, `value`) VALUES ('FO', 'جزر فارو');
INSERT INTO `countries` (`id`, `value`) VALUES ('FK', 'جزر فوكلاند');
INSERT INTO `countries` (`id`, `value`) VALUES ('VG', 'جزر فيرجن البريطانية');
INSERT INTO `countries` (`id`, `value`) VALUES ('VI', 'جزر فيرجن التابعة للولايات المتحدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('KY', 'جزر كايمان');
INSERT INTO `countries` (`id`, `value`) VALUES ('CK', 'جزر كوك');
INSERT INTO `countries` (`id`, `value`) VALUES ('CC', 'جزر كوكوس (كيلينغ)');
INSERT INTO `countries` (`id`, `value`) VALUES ('MH', 'جزر مارشال');
INSERT INTO `countries` (`id`, `value`) VALUES ('MP', 'جزر ماريانا الشمالية');
INSERT INTO `countries` (`id`, `value`) VALUES ('WF', 'جزر والس وفوتونا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BV', 'جزيرة بوفيه');
INSERT INTO `countries` (`id`, `value`) VALUES ('CX', 'جزيرة كريسماس');
INSERT INTO `countries` (`id`, `value`) VALUES ('IM', 'جزيرة مان');
INSERT INTO `countries` (`id`, `value`) VALUES ('NF', 'جزيرة نورفولك');
INSERT INTO `countries` (`id`, `value`) VALUES ('HM', 'جزيرة هيرد وجزر ماكدونالد');
INSERT INTO `countries` (`id`, `value`) VALUES ('CF', 'جمهورية أفريقيا الوسطى');
INSERT INTO `countries` (`id`, `value`) VALUES ('DO', 'جمهورية الدومينيكان');
INSERT INTO `countries` (`id`, `value`) VALUES ('ZA', 'جنوب أفريقيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SS', 'جنوب السودان');
INSERT INTO `countries` (`id`, `value`) VALUES ('GE', 'جورجيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GS', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية');
INSERT INTO `countries` (`id`, `value`) VALUES ('DJ', 'جيبوتي');
INSERT INTO `countries` (`id`, `value`) VALUES ('JE', 'جيرسي');
INSERT INTO `countries` (`id`, `value`) VALUES ('DM', 'دومينيكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('RW', 'رواندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('RU', 'روسيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('RO', 'رومانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('RE', 'روينيون');
INSERT INTO `countries` (`id`, `value`) VALUES ('ZM', 'زامبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ZW', 'زيمبابوي');
INSERT INTO `countries` (`id`, `value`) VALUES ('CI', 'ساحل العاج');
INSERT INTO `countries` (`id`, `value`) VALUES ('WS', 'ساموا');
INSERT INTO `countries` (`id`, `value`) VALUES ('AS', 'ساموا الأمريكية');
INSERT INTO `countries` (`id`, `value`) VALUES ('BL', 'سان بارتليمي');
INSERT INTO `countries` (`id`, `value`) VALUES ('PM', 'سان بيير ومكويلون');
INSERT INTO `countries` (`id`, `value`) VALUES ('MF', 'سان مارتن');
INSERT INTO `countries` (`id`, `value`) VALUES ('SM', 'سان مارينو');
INSERT INTO `countries` (`id`, `value`) VALUES ('VC', 'سانت فنسنت وجزر غرينادين');
INSERT INTO `countries` (`id`, `value`) VALUES ('KN', 'سانت كيتس ونيفيس');
INSERT INTO `countries` (`id`, `value`) VALUES ('LC', 'سانت لوسيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SX', 'سانت مارتن');
INSERT INTO `countries` (`id`, `value`) VALUES ('SH', 'سانت هيلينا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ST', 'ساو تومي وبرينسيبي');
INSERT INTO `countries` (`id`, `value`) VALUES ('LK', 'سريلانكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SJ', 'سفالبارد وجان ماين');
INSERT INTO `countries` (`id`, `value`) VALUES ('SK', 'سلوفاكيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SI', 'سلوفينيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SG', 'سنغافورة');
INSERT INTO `countries` (`id`, `value`) VALUES ('SY', 'سوريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SR', 'سورينام');
INSERT INTO `countries` (`id`, `value`) VALUES ('CH', 'سويسرا');
INSERT INTO `countries` (`id`, `value`) VALUES ('SL', 'سيراليون');
INSERT INTO `countries` (`id`, `value`) VALUES ('SC', 'سيشل');
INSERT INTO `countries` (`id`, `value`) VALUES ('RS', 'صربيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('TJ', 'طاجيكستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('OM', 'عُمان');
INSERT INTO `countries` (`id`, `value`) VALUES ('GM', 'غامبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GH', 'غانا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GD', 'غرينادا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GL', 'غرينلاند');
INSERT INTO `countries` (`id`, `value`) VALUES ('GT', 'غواتيمالا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GP', 'غوادلوب');
INSERT INTO `countries` (`id`, `value`) VALUES ('GU', 'غوام');
INSERT INTO `countries` (`id`, `value`) VALUES ('GF', 'غويانا الفرنسية');
INSERT INTO `countries` (`id`, `value`) VALUES ('GY', 'غيانا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GG', 'غيرنزي');
INSERT INTO `countries` (`id`, `value`) VALUES ('GN', 'غينيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('GQ', 'غينيا الاستوائية');
INSERT INTO `countries` (`id`, `value`) VALUES ('GW', 'غينيا بيساو');
INSERT INTO `countries` (`id`, `value`) VALUES ('VU', 'فانواتو');
INSERT INTO `countries` (`id`, `value`) VALUES ('FR', 'فرنسا');
INSERT INTO `countries` (`id`, `value`) VALUES ('VE', 'فنزويلا');
INSERT INTO `countries` (`id`, `value`) VALUES ('FI', 'فنلندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('VN', 'فيتنام');
INSERT INTO `countries` (`id`, `value`) VALUES ('FJ', 'فيجي');
INSERT INTO `countries` (`id`, `value`) VALUES ('CY', 'قبرص');
INSERT INTO `countries` (`id`, `value`) VALUES ('QA', 'قطر');
INSERT INTO `countries` (`id`, `value`) VALUES ('KG', 'قيرغيزستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('KZ', 'كازاخستان');
INSERT INTO `countries` (`id`, `value`) VALUES ('NC', 'كاليدونيا الجديدة');
INSERT INTO `countries` (`id`, `value`) VALUES ('HR', 'كرواتيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('KH', 'كمبوديا');
INSERT INTO `countries` (`id`, `value`) VALUES ('CA', 'كندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('CU', 'كوبا');
INSERT INTO `countries` (`id`, `value`) VALUES ('CW', 'كوراساو');
INSERT INTO `countries` (`id`, `value`) VALUES ('KR', 'كوريا الجنوبية');
INSERT INTO `countries` (`id`, `value`) VALUES ('KP', 'كوريا الشمالية');
INSERT INTO `countries` (`id`, `value`) VALUES ('CR', 'كوستاريكا');
INSERT INTO `countries` (`id`, `value`) VALUES ('CO', 'كولومبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('KI', 'كيريباتي');
INSERT INTO `countries` (`id`, `value`) VALUES ('KE', 'كينيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('LV', 'لاتفيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('LA', 'لاوس');
INSERT INTO `countries` (`id`, `value`) VALUES ('LB', 'لبنان');
INSERT INTO `countries` (`id`, `value`) VALUES ('LU', 'لوكسمبورغ');
INSERT INTO `countries` (`id`, `value`) VALUES ('LY', 'ليبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('LR', 'ليبيريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('LT', 'ليتوانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('LI', 'ليختنشتاين');
INSERT INTO `countries` (`id`, `value`) VALUES ('LS', 'ليسوتو');
INSERT INTO `countries` (`id`, `value`) VALUES ('MT', 'مالطا');
INSERT INTO `countries` (`id`, `value`) VALUES ('ML', 'مالي');
INSERT INTO `countries` (`id`, `value`) VALUES ('MY', 'ماليزيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('YT', 'مايوت');
INSERT INTO `countries` (`id`, `value`) VALUES ('MG', 'مدغشقر');
INSERT INTO `countries` (`id`, `value`) VALUES ('EG', 'مصر');
INSERT INTO `countries` (`id`, `value`) VALUES ('MK', 'مقدونيا الشمالية');
INSERT INTO `countries` (`id`, `value`) VALUES ('MW', 'ملاوي');
INSERT INTO `countries` (`id`, `value`) VALUES ('MO', 'منطقة ماكاو الإدارية الخاصة');
INSERT INTO `countries` (`id`, `value`) VALUES ('MN', 'منغوليا');
INSERT INTO `countries` (`id`, `value`) VALUES ('MR', 'موريتانيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('MU', 'موريشيوس');
INSERT INTO `countries` (`id`, `value`) VALUES ('MZ', 'موزمبيق');
INSERT INTO `countries` (`id`, `value`) VALUES ('MD', 'مولدوفا');
INSERT INTO `countries` (`id`, `value`) VALUES ('MC', 'موناكو');
INSERT INTO `countries` (`id`, `value`) VALUES ('MS', 'مونتسرات');
INSERT INTO `countries` (`id`, `value`) VALUES ('MM', 'ميانمار (بورما)');
INSERT INTO `countries` (`id`, `value`) VALUES ('FM', 'ميكرونيزيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NA', 'ناميبيا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NR', 'ناورو');
INSERT INTO `countries` (`id`, `value`) VALUES ('NP', 'نيبال');
INSERT INTO `countries` (`id`, `value`) VALUES ('NG', 'نيجيريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NI', 'نيكاراغوا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NZ', 'نيوزيلندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NU', 'نيوي');
INSERT INTO `countries` (`id`, `value`) VALUES ('HT', 'هايتي');
INSERT INTO `countries` (`id`, `value`) VALUES ('HN', 'هندوراس');
INSERT INTO `countries` (`id`, `value`) VALUES ('HU', 'هنغاريا');
INSERT INTO `countries` (`id`, `value`) VALUES ('NL', 'هولندا');
INSERT INTO `countries` (`id`, `value`) VALUES ('BQ', 'هولندا الكاريبية');
INSERT INTO `countries` (`id`, `value`) VALUES ('HK', 'هونغ كونغ الصينية (منطقة إدارية خاصة)');